server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: AuthService
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/user/**
        - id: TaskManagerService
          uri: lb://TASKMANAGERSERVICE
          predicates:
            - Path=/task/**