server:
  port: 8081

spring:
  application:
    name: AUTHSERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/task_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret:
    key: mySuperSecretKeyThatIsAtLeast32CharsLong123

logging:
  file:
    name: logs/AuthService.log
  level:
    root: INFO


    